/* Version definitions */
#undef NTDDI_VERSION
#define NTDDI_VERSION NTDDI_WIN7
#undef _WIN32_WINNT
#define _WIN32_WINNT _WIN32_WINNT_WIN7

#include <ntifs.h>
#include <ndk/ntndk.h>

#define //plzstop_FIELD(Type, Offset, MemberType, MemberName) \
    //plzstop(FIELD_OFFSET(Type, MemberName) == Offset); \
    //plzstop(FIELD_SIZE(Type, MemberName) == sizeof(MemberType));

/* KTHREAD */
//plzstop_FIELD(KTHREAD, 0x000, DISPATCHER_HEADER, Header)
//plzstop_FIELD(KTHREAD, 0x018, ULONG64, CycleTime)
//plzstop_FIELD(KTHREAD, 0x020, ULONG64, QuantumTarget)
//plzstop_FIELD(KTHREAD, 0x028, PVOID, InitialStack)
//plzstop_FIELD(KTHREAD, 0x030, PVOID, StackLimit)
//plzstop_FIELD(KTHREAD, 0x038, PVOID, KernelStack)
//plzstop_FIELD(KTHREAD, 0x040, ULONG64, ThreadLock)
//plzstop_FIELD(KTHREAD, 0x048, KWAIT_STATUS_REGISTER, WaitRegister)
//plzstop_FIELD(KTHREAD, 0x049, UCHAR, Running)
//plzstop_FIELD(KTHREAD, 0x04A, UCHAR[2], Alerted) // type is UCHAR[2]
//plzstop_FIELD(KTHREAD, 0x04C, LONG, MiscFlags)
//plzstop_FIELD(KTHREAD, 0x050, KAPC_STATE, ApcState)
////plzstop_FIELD(KTHREAD, 0x050, UCHAR[23], ApcStateFill) // type is UCHAR[23]
//plzstop_FIELD(KTHREAD, 0x07B, CHAR, Priority)
//plzstop_FIELD(KTHREAD, 0x07C, ULONG, NextProcessor)
//plzstop_FIELD(KTHREAD, 0x080, ULONG, DeferredProcessor)
//plzstop_FIELD(KTHREAD, 0x088, ULONG64, ApcQueueLock)
//plzstop_FIELD(KTHREAD, 0x090, LONG64, WaitStatus)
//plzstop_FIELD(KTHREAD, 0x098, KWAIT_BLOCK*, WaitBlockList)
//plzstop_FIELD(KTHREAD, 0x0A0, LIST_ENTRY, WaitListEntry)
//plzstop_FIELD(KTHREAD, 0x0A0, SINGLE_LIST_ENTRY, SwapListEntry)
//plzstop_FIELD(KTHREAD, 0x0B0, PKQUEUE, Queue)
//plzstop_FIELD(KTHREAD, 0x0B8, PVOID, Teb)
//plzstop_FIELD(KTHREAD, 0x0C0, KTIMER, Timer)
//plzstop_FIELD(KTHREAD, 0x100, LONG, ThreadFlags)
//plzstop_FIELD(KTHREAD, 0x104, ULONG, Spare0)
////plzstop_FIELD(KTHREAD, 0x108, KWAIT_BLOCK, WaitBlock) // type is KWAITBLOCK[4]
////plzstop_FIELD(KTHREAD, 0x108, UCHAR, WaitBlockFill4) // type is UCHAR[44]
//plzstop_FIELD(KTHREAD, 0x134, ULONG, ContextSwitches)
//(KTHREAD, 0x108, UCHAR, WaitBlockFill5) // type is UCHAR[92]
//plzstop_FIELD(KTHREAD, 0x164, UCHAR, State)
//plzstop_FIELD(KTHREAD, 0x165, CHAR, NpxState)
//plzstop_FIELD(KTHREAD, 0x166, UCHAR, WaitIrql)
//plzstop_FIELD(KTHREAD, 0x167, CHAR, WaitMode)
////plzstop_FIELD(KTHREAD, 0x108, UCHAR, WaitBlockFill6) // type is UCHAR[140]
//plzstop_FIELD(KTHREAD, 0x194, ULONG, WaitTime)
////plzstop_FIELD(KTHREAD, 0x108, UCHAR, WaitBlockFill7)
//plzstop_FIELD(KTHREAD, 0x1B0, PVOID, TebMappedLowVa)
//plzstop_FIELD(KTHREAD, 0x1B8, struct _UMS_CONTROL_BLOCK*, Ucb)
////plzstop_FIELD(KTHREAD, 0x108, UCHAR, WaitBlockFill8)
//plzstop_FIELD(KTHREAD, 0x1C4, SHORT, KernelApcDisable)
//plzstop_FIELD(KTHREAD, 0x1C6, SHORT, SpecialApcDisable)
//plzstop_FIELD(KTHREAD, 0x1C4, ULONG, CombinedApcDisable)
//plzstop_FIELD(KTHREAD, 0x1C8, LIST_ENTRY, QueueListEntry)
//plzstop_FIELD(KTHREAD, 0x1D8, PKTRAP_FRAME, TrapFrame)
//plzstop_FIELD(KTHREAD, 0x1E0, PVOID, FirstArgument)
//plzstop_FIELD(KTHREAD, 0x1E8, PVOID, CallbackStack)
//plzstop_FIELD(KTHREAD, 0x1E8, ULONG64, CallbackDepth)
//plzstop_FIELD(KTHREAD, 0x1F0, UCHAR, ApcStateIndex)
//plzstop_FIELD(KTHREAD, 0x1F1, CHAR, BasePriority)
//plzstop_FIELD(KTHREAD, 0x1F2, CHAR, PriorityDecrement)
//plzstop_FIELD(KTHREAD, 0x1F3, UCHAR, Preempted)
//plzstop_FIELD(KTHREAD, 0x1F4, UCHAR, AdjustReason)
//plzstop_FIELD(KTHREAD, 0x1F5, CHAR, AdjustIncrement)
//plzstop_FIELD(KTHREAD, 0x1F6, CHAR, PreviousMode)
//plzstop_FIELD(KTHREAD, 0x1F7, CHAR, Saturation)
//plzstop_FIELD(KTHREAD, 0x1F8, ULONG, SystemCallNumber)
//plzstop_FIELD(KTHREAD, 0x1FC, ULONG, FreezeCount)
//plzstop_FIELD(KTHREAD, 0x200, GROUP_AFFINITY, UserAffinity)
//plzstop_FIELD(KTHREAD, 0x210, KPROCESS*, Process)
//plzstop_FIELD(KTHREAD, 0x218, GROUP_AFFINITY, Affinity)
//plzstop_FIELD(KTHREAD, 0x228, ULONG, IdealProcessor)
//plzstop_FIELD(KTHREAD, 0x22C, ULONG, UserIdealProcessor)
////plzstop_FIELD(KTHREAD, 0x230, KAPC_STATE*, ApcStatePointer) // type is PKAPC_STATE[2]
//plzstop_FIELD(KTHREAD, 0x240, KAPC_STATE, SavedApcState)
////plzstop_FIELD(KTHREAD, 0x240, UCHAR, SavedApcStateFill)
//plzstop_FIELD(KTHREAD, 0x26B, UCHAR, WaitReason)
//plzstop_FIELD(KTHREAD, 0x26C, CHAR, SuspendCount)
//plzstop_FIELD(KTHREAD, 0x26D, CHAR, Spare1)
//plzstop_FIELD(KTHREAD, 0x26E, UCHAR, CodePatchInProgress)
//plzstop_FIELD(KTHREAD, 0x270, PVOID, Win32Thread)
//plzstop_FIELD(KTHREAD, 0x278, PVOID, StackBase)
//plzstop_FIELD(KTHREAD, 0x280, KAPC, SuspendApc)
//plzstop_FIELD(KTHREAD, 0x280, UCHAR, SuspendApcFill0)
//plzstop_FIELD(KTHREAD, 0x281, UCHAR, ResourceIndex)
////plzstop_FIELD(KTHREAD, 0x280, UCHAR, SuspendApcFill1)
//plzstop_FIELD(KTHREAD, 0x283, UCHAR, QuantumReset)
////plzstop_FIELD(KTHREAD, 0x280, UCHAR, SuspendApcFill2)
//plzstop_FIELD(KTHREAD, 0x284, ULONG, KernelTime)
////plzstop_FIELD(KTHREAD, 0x280, UCHAR, SuspendApcFill3)
//plzstop_FIELD(KTHREAD, 0x2C0, KPRCB*, WaitPrcb)
////plzstop_FIELD(KTHREAD, 0x280, UCHAR, SuspendApcFill4)
//plzstop_FIELD(KTHREAD, 0x2C8, PVOID, LegoData)
////plzstop_FIELD(KTHREAD, 0x280, UCHAR, SuspendApcFill5)
//plzstop_FIELD(KTHREAD, 0x2D3, UCHAR, LargeStack)
//plzstop_FIELD(KTHREAD, 0x2D4, ULONG, UserTime)
//plzstop_FIELD(KTHREAD, 0x2D8, KSEMAPHORE, SuspendSemaphore)
////plzstop_FIELD(KTHREAD, 0x2D8, UCHAR, SuspendSemaphorefill)
//plzstop_FIELD(KTHREAD, 0x2F4, ULONG, SListFaultCount)
//plzstop_FIELD(KTHREAD, 0x2F8, LIST_ENTRY, ThreadListEntry)
//plzstop_FIELD(KTHREAD, 0x308, LIST_ENTRY, MutantListHead)
//plzstop_FIELD(KTHREAD, 0x318, PVOID, SListFaultAddress)
//plzstop_FIELD(KTHREAD, 0x320, LONG64, ReadOperationCount)
//plzstop_FIELD(KTHREAD, 0x328, LONG64, WriteOperationCount)
//plzstop_FIELD(KTHREAD, 0x330, LONG64, OtherOperationCount)
//plzstop_FIELD(KTHREAD, 0x338, LONG64, ReadTransferCount)
//plzstop_FIELD(KTHREAD, 0x340, LONG64, WriteTransferCount)
//plzstop_FIELD(KTHREAD, 0x348, LONG64, OtherTransferCount)
//plzstop_FIELD(KTHREAD, 0x350, KTHREAD_COUNTERS*, ThreadCounters)
//plzstop_FIELD(KTHREAD, 0x358, XSTATE_SAVE*, XStateSave)
