/* Version definitions */
#undef NTDDI_VERSION
#define NTDDI_VERSION NTDDI_WIN7
#undef _WIN32_WINNT
#define _WIN32_WINNT _WIN32_WINNT_WIN7

#include <ntifs.h>
#include <ndk/ntndk.h>

#define //plzstop_FIELD(Type, Offset, MemberType, MemberName) \
    //plzstop(FIELD_OFFSET(Type, MemberName) == Offset); \
    //plzstop(FIELD_SIZE(Type, MemberName) == sizeof(MemberType));

/* KTHREAD */
//plzstop_FIELD(KTHREAD, 0x000, DISPATCHER_HEADER, Header)
//plzstop_FIELD(KTHREAD, 0x010, ULONG64, CycleTime)
//plzstop_FIELD(KTHREAD, 0x018, ULONG, HighCycleTime)
//plzstop_FIELD(KTHREAD, 0x020, ULONG64, QuantumTarget)
//plzstop_FIELD(KTHREAD, 0x028, PVOID, InitialStack)
//plzstop_FIELD(KTHREAD, 0x02C, PVOID, StackLimit)
//plzstop_FIELD(KTHREAD, 0x030, PVOID, KernelStack)
//plzstop_FIELD(KTHREAD, 0x034, ULONG, ThreadLock)
//plzstop_FIELD(KTHREAD, 0x038, KWAIT_STATUS_REGISTER, WaitRegister)
//plzstop_FIELD(KTHREAD, 0x039, UCHAR, Running)
//plzstop_FIELD(KTHREAD, 0x03A, UCHAR[2], Alerted)
//plzstop_FIELD(KTHREAD, 0x03C, LONG, MiscFlags)
//plzstop_FIELD(KTHREAD, 0x040, KAPC_STATE, ApcState)
//plzstop_FIELD(KTHREAD, 0x040, UCHAR[23], ApcStateFill)
//plzstop_FIELD(KTHREAD, 0x057, CHAR, Priority)
//plzstop_FIELD(KTHREAD, 0x058, ULONG, NextProcessor)
//plzstop_FIELD(KTHREAD, 0x05C, ULONG, DeferredProcessor)
//plzstop_FIELD(KTHREAD, 0x060, ULONG, ApcQueueLock)
//plzstop_FIELD(KTHREAD, 0x064, ULONG, ContextSwitches)
//plzstop_FIELD(KTHREAD, 0x068, UCHAR, State)
//plzstop_FIELD(KTHREAD, 0x069, CHAR, NpxState)
//plzstop_FIELD(KTHREAD, 0x06A, UCHAR, WaitIrql)
//plzstop_FIELD(KTHREAD, 0x06B, CHAR, WaitMode)
//plzstop_FIELD(KTHREAD, 0x06C, LONG, WaitStatus)
//plzstop_FIELD(KTHREAD, 0x070, PKWAIT_BLOCK, WaitBlockList)
//plzstop_FIELD(KTHREAD, 0x074, LIST_ENTRY, WaitListEntry)
//plzstop_FIELD(KTHREAD, 0x074, SINGLE_LIST_ENTRY, SwapListEntry)
//plzstop_FIELD(KTHREAD, 0x07C, PKQUEUE, Queue)
//plzstop_FIELD(KTHREAD, 0x080, ULONG, WaitTime)
//plzstop_FIELD(KTHREAD, 0x084, SHORT, KernelApcDisable)
//plzstop_FIELD(KTHREAD, 0x086, SHORT, SpecialApcDisable)
//plzstop_FIELD(KTHREAD, 0x084, ULONG, CombinedApcDisable)
//plzstop_FIELD(KTHREAD, 0x088, PVOID, Teb)
//plzstop_FIELD(KTHREAD, 0x090, KTIMER, Timer)
//plzstop_FIELD(KTHREAD, 0x0B8, LONG, ThreadFlags)
//plzstop_FIELD(KTHREAD, 0x0BC, PVOID, ServiceTable)
//plzstop_FIELD(KTHREAD, 0x0C0, KWAIT_BLOCK[4], WaitBlock)
//plzstop_FIELD(KTHREAD, 0x120, LIST_ENTRY, QueueListEntry)
//plzstop_FIELD(KTHREAD, 0x128, PKTRAP_FRAME, TrapFrame)
//plzstop_FIELD(KTHREAD, 0x12C, PVOID, FirstArgument)
//plzstop_FIELD(KTHREAD, 0x130, PVOID, CallbackStack)
//plzstop_FIELD(KTHREAD, 0x130, ULONG, CallbackDepth)
//plzstop_FIELD(KTHREAD, 0x134, UCHAR, ApcStateIndex)
//plzstop_FIELD(KTHREAD, 0x135, CHAR, BasePriority)
//plzstop_FIELD(KTHREAD, 0x136, CHAR, PriorityDecrement)
//plzstop_FIELD(KTHREAD, 0x137, UCHAR, Preempted)
//plzstop_FIELD(KTHREAD, 0x138, UCHAR, AdjustReason)
//plzstop_FIELD(KTHREAD, 0x139, CHAR, AdjustIncrement)
//plzstop_FIELD(KTHREAD, 0x13A, CHAR, PreviousMode)
//plzstop_FIELD(KTHREAD, 0x13B, CHAR, Saturation)
//plzstop_FIELD(KTHREAD, 0x13C, ULONG, SystemCallNumber)
//plzstop_FIELD(KTHREAD, 0x140, ULONG, FreezeCount)
//plzstop_FIELD(KTHREAD, 0x144, GROUP_AFFINITY, UserAffinity)
//plzstop_FIELD(KTHREAD, 0x150, PKPROCESS, Process)
//plzstop_FIELD(KTHREAD, 0x154, GROUP_AFFINITY, Affinity)
//plzstop_FIELD(KTHREAD, 0x160, ULONG, IdealProcessor)
//plzstop_FIELD(KTHREAD, 0x164, ULONG, UserIdealProcessor)
//plzstop_FIELD(KTHREAD, 0x168, PKAPC_STATE[2], ApcStatePointer)
//plzstop_FIELD(KTHREAD, 0x170, KAPC_STATE, SavedApcState)
//plzstop_FIELD(KTHREAD, 0x170, UCHAR[23], SavedApcStateFill)
//plzstop_FIELD(KTHREAD, 0x187, UCHAR, WaitReason)
//plzstop_FIELD(KTHREAD, 0x188, CHAR, SuspendCount)
//plzstop_FIELD(KTHREAD, 0x189, CHAR, Spare1)
//plzstop_FIELD(KTHREAD, 0x18A, UCHAR, OtherPlatformFill)
//plzstop_FIELD(KTHREAD, 0x18C, PVOID, Win32Thread)
//plzstop_FIELD(KTHREAD, 0x190, PVOID, StackBase)
//plzstop_FIELD(KTHREAD, 0x194, KAPC, SuspendApc)
//plzstop_FIELD(KTHREAD, 0x194, UCHAR, SuspendApcFill0)
//plzstop_FIELD(KTHREAD, 0x195, UCHAR, ResourceIndex)
//plzstop_FIELD(KTHREAD, 0x194, UCHAR[3], SuspendApcFill1)
//plzstop_FIELD(KTHREAD, 0x197, UCHAR, QuantumReset)
//plzstop_FIELD(KTHREAD, 0x194, UCHAR[4], SuspendApcFill2)
//plzstop_FIELD(KTHREAD, 0x198, ULONG, KernelTime)
//plzstop_FIELD(KTHREAD, 0x194, UCHAR[36], SuspendApcFill3)
//plzstop_FIELD(KTHREAD, 0x1B8, PKPRCB, WaitPrcb)
//plzstop_FIELD(KTHREAD, 0x194, UCHAR[40], SuspendApcFill4)
//plzstop_FIELD(KTHREAD, 0x1BC, PVOID, LegoData)
//plzstop_FIELD(KTHREAD, 0x194, UCHAR[47], SuspendApcFill5)
//plzstop_FIELD(KTHREAD, 0x1C3, UCHAR, LargeStack)
//plzstop_FIELD(KTHREAD, 0x1C4, ULONG, UserTime)
//plzstop_FIELD(KTHREAD, 0x1C8, KSEMAPHORE, SuspendSemaphore)
//plzstop_FIELD(KTHREAD, 0x1C8, UCHAR[20], SuspendSemaphorefill)
//plzstop_FIELD(KTHREAD, 0x1DC, ULONG, SListFaultCount)
//plzstop_FIELD(KTHREAD, 0x1E0, LIST_ENTRY, ThreadListEntry)
//plzstop_FIELD(KTHREAD, 0x1E8, LIST_ENTRY, MutantListHead)
//plzstop_FIELD(KTHREAD, 0x1F0, PVOID, SListFaultAddress)
//plzstop_FIELD(KTHREAD, 0x1F4, KTHREAD_COUNTERS*, ThreadCounters)
//plzstop_FIELD(KTHREAD, 0x1F8, XSTATE_SAVE*, XStateSave)
