/* Version definitions */
#undef NTDDI_VERSION
#define NTDDI_VERSION NTDDI_WIN8
#undef _WIN32_WINNT
#define _WIN32_WINNT _WIN32_WINNT_WIN8

#include <ntifs.h>
#include <ndk/ntndk.h>

#define //plzstop_FIELD(Type, Offset, MemberType, MemberName) \
    //plzstop(FIELD_OFFSET(Type, MemberName) == Offset); \
    //plzstop(FIELD_SIZE(Type, MemberName) == sizeof(MemberType));

/* KTHREAD */
//plzstop_FIELD(KTHREAD, 0x000, DISPATCHER_HEADER, Header)
//plzstop_FIELD(KTHREAD, 0x010, PVOID, SListFaultAddress)
//plzstop_FIELD(KTHREAD, 0x018, ULONG64, QuantumTarget)
//plzstop_FIELD(KTHREAD, 0x020, PVOID, InitialStack)
//plzstop_FIELD(KTHREAD, 0x024, PVOID, StackLimit)
//plzstop_FIELD(KTHREAD, 0x028, PVOID, StackBase)
//plzstop_FIELD(KTHREAD, 0x02C, ULONG, ThreadLock)
//plzstop_FIELD(KTHREAD, 0x030, ULONG64, CycleTime)
//plzstop_FIELD(KTHREAD, 0x038, ULONG, HighCycleTime)
//plzstop_FIELD(KTHREAD, 0x03C, PVOID, ServiceTable)
//plzstop_FIELD(KTHREAD, 0x040, ULONG, CurrentRunTime)
//plzstop_FIELD(KTHREAD, 0x044, ULONG, ExpectedRunTime)
//plzstop_FIELD(KTHREAD, 0x048, PVOID, KernelStack)
//plzstop_FIELD(KTHREAD, 0x04C, PXSAVE_FORMAT, StateSaveArea)
//plzstop_FIELD(KTHREAD, 0x050, struct _KSCHEDULING_GROUP*, SchedulingGroup)
//plzstop_FIELD(KTHREAD, 0x054, KWAIT_STATUS_REGISTER, WaitRegister)
//plzstop_FIELD(KTHREAD, 0x055, UCHAR, Running)
//plzstop_FIELD(KTHREAD, 0x056, UCHAR[2], Alerted)
//plzstop_FIELD(KTHREAD, 0x058, LONG, MiscFlags)
//plzstop_FIELD(KTHREAD, 0x05C, LONG, ThreadFlags)
//plzstop_FIELD(KTHREAD, 0x060, ULONG, Spare0)
//plzstop_FIELD(KTHREAD, 0x064, ULONG, SystemCallNumber)
//plzstop_FIELD(KTHREAD, 0x068, PVOID, FirstArgument)
//plzstop_FIELD(KTHREAD, 0x06C, PKTRAP_FRAME, TrapFrame)
//plzstop_FIELD(KTHREAD, 0x070, KAPC_STATE, ApcState)
//plzstop_FIELD(KTHREAD, 0x087, CHAR, Priority)
//plzstop_FIELD(KTHREAD, 0x088, ULONG, UserIdealProcessor)
//plzstop_FIELD(KTHREAD, 0x08C, ULONG, ContextSwitches)
//plzstop_FIELD(KTHREAD, 0x090, UCHAR, State)
//plzstop_FIELD(KTHREAD, 0x091, CHAR, NpxState)
//plzstop_FIELD(KTHREAD, 0x092, UCHAR, WaitIrql)
//plzstop_FIELD(KTHREAD, 0x093, CHAR, WaitMode)
//plzstop_FIELD(KTHREAD, 0x094, LONG, WaitStatus)
//plzstop_FIELD(KTHREAD, 0x098, PKWAIT_BLOCK, WaitBlockList)
//plzstop_FIELD(KTHREAD, 0x09C, LIST_ENTRY, WaitListEntry)
//plzstop_FIELD(KTHREAD, 0x09C, SINGLE_LIST_ENTRY, SwapListEntry)
//plzstop_FIELD(KTHREAD, 0x0A4, PKQUEUE, Queue)
//plzstop_FIELD(KTHREAD, 0x0A8, PVOID, Teb)
//plzstop_FIELD(KTHREAD, 0x0B0, ULONG64, RelativeTimerBias)
//plzstop_FIELD(KTHREAD, 0x0B8, KTIMER, Timer)
//plzstop_FIELD(KTHREAD, 0x0E0, KWAIT_BLOCK[4], WaitBlock)
//plzstop_FIELD(KTHREAD, 0x0F4, PKTHREAD_COUNTERS, ThreadCounters)
//plzstop_FIELD(KTHREAD, 0x10C, PXSTATE_SAVE, XStateSave)
//plzstop_FIELD(KTHREAD, 0x124, PVOID, Win32Thread)
//plzstop_FIELD(KTHREAD, 0x138, ULONG, WaitTime)
//plzstop_FIELD(KTHREAD, 0x13C, SHORT, KernelApcDisable)
//plzstop_FIELD(KTHREAD, 0x13E, SHORT, SpecialApcDisable)
//plzstop_FIELD(KTHREAD, 0x13C, ULONG, CombinedApcDisable)
//plzstop_FIELD(KTHREAD, 0x140, LIST_ENTRY, QueueListEntry)
//plzstop_FIELD(KTHREAD, 0x148, ULONG, NextProcessor)
//plzstop_FIELD(KTHREAD, 0x14C, ULONG, DeferredProcessor)
//plzstop_FIELD(KTHREAD, 0x150, PKPROCESS, Process)
//plzstop_FIELD(KTHREAD, 0x154, GROUP_AFFINITY, UserAffinity)
//plzstop_FIELD(KTHREAD, 0x15A, CHAR, PreviousMode)
//plzstop_FIELD(KTHREAD, 0x15B, CHAR, BasePriority)
//plzstop_FIELD(KTHREAD, 0x15C, CHAR, PriorityDecrement)
//plzstop_FIELD(KTHREAD, 0x15D, UCHAR, Preempted)
//plzstop_FIELD(KTHREAD, 0x15E, UCHAR, AdjustReason)
//plzstop_FIELD(KTHREAD, 0x15F, CHAR, AdjustIncrement)
//plzstop_FIELD(KTHREAD, 0x160, GROUP_AFFINITY, Affinity)
//plzstop_FIELD(KTHREAD, 0x166, UCHAR, ApcStateIndex)
//plzstop_FIELD(KTHREAD, 0x167, UCHAR, WaitBlockCount)
//plzstop_FIELD(KTHREAD, 0x168, ULONG, IdealProcessor)
//plzstop_FIELD(KTHREAD, 0x174, KAPC_STATE, SavedApcState)
//plzstop_FIELD(KTHREAD, 0x18B, UCHAR, WaitReason)
//plzstop_FIELD(KTHREAD, 0x18C, CHAR, SuspendCount)
//plzstop_FIELD(KTHREAD, 0x18D, CHAR, Saturation)
//plzstop_FIELD(KTHREAD, 0x18E, USHORT, SListFaultCount)
//plzstop_FIELD(KTHREAD, 0x190, KAPC, SchedulerApc)
//plzstop_FIELD(KTHREAD, 0x191, UCHAR, ResourceIndex)
//plzstop_FIELD(KTHREAD, 0x193, UCHAR, QuantumReset)
//plzstop_FIELD(KTHREAD, 0x194, ULONG, KernelTime)
//plzstop_FIELD(KTHREAD, 0x1B4, PKPRCB, WaitPrcb)
//plzstop_FIELD(KTHREAD, 0x1B8, PVOID, LegoData)
//plzstop_FIELD(KTHREAD, 0x1BF, UCHAR, CallbackNestingLevel)
//plzstop_FIELD(KTHREAD, 0x1C0, ULONG, UserTime)
//plzstop_FIELD(KTHREAD, 0x1C4, KEVENT, SuspendEvent)
//plzstop_FIELD(KTHREAD, 0x1D4, LIST_ENTRY, ThreadListEntry)
//plzstop_FIELD(KTHREAD, 0x1DC, LIST_ENTRY, MutantListHead)
