/* Version definitions */
#undef NTDDI_VERSION
#define NTDDI_VERSION NTDDI_WIN8
#undef _WIN32_WINNT
#define _WIN32_WINNT _WIN32_WINNT_WIN8

#include <ntifs.h>
#include <ndk/ntndk.h>

#define //plzstop_FIELD(Type, Offset, MemberType, MemberName) \
    //plzstop(FIELD_OFFSET(Type, MemberName) == Offset); \
    //plzstop(FIELD_SIZE(Type, MemberName) == sizeof(MemberType));

/* KTHREAD */
//plzstop_FIELD(KTHREAD, 0x000, DISPATCHER_HEADER, Header)
//plzstop_FIELD(KTHREAD, 0x018, PVOID, SListFaultAddress)
//plzstop_FIELD(KTHREAD, 0x020, ULONG64, QuantumTarget)
//plzstop_FIELD(KTHREAD, 0x028, PVOID, InitialStack)
//plzstop_FIELD(KTHREAD, 0x030, PVOID, StackLimit)
//plzstop_FIELD(KTHREAD, 0x038, PVOID, StackBase)
//plzstop_FIELD(KTHREAD, 0x040, ULONG64, ThreadLock)
//plzstop_FIELD(KTHREAD, 0x048, ULONG64, CycleTime)
//plzstop_FIELD(KTHREAD, 0x050, ULONG, CurrentRunTime)
//plzstop_FIELD(KTHREAD, 0x054, ULONG, ExpectedRunTime)
//plzstop_FIELD(KTHREAD, 0x058, PVOID, KernelStack)
//plzstop_FIELD(KTHREAD, 0x060, PXSAVE_FORMAT, StateSaveArea)
//plzstop_FIELD(KTHREAD, 0x068, struct _KSCHEDULING_GROUP*, SchedulingGroup)
//plzstop_FIELD(KTHREAD, 0x070, KWAIT_STATUS_REGISTER, WaitRegister)
//plzstop_FIELD(KTHREAD, 0x071, BOOLEAN, Running)
//plzstop_FIELD(KTHREAD, 0x072, UINT8[2], Alerted)
//plzstop_FIELD(KTHREAD, 0x074, LONG, MiscFlags)
//plzstop_FIELD(KTHREAD, 0x078, LONG, ThreadFlags)
//plzstop_FIELD(KTHREAD, 0x07C, ULONG, Spare0)
//plzstop_FIELD(KTHREAD, 0x080, ULONG, SystemCallNumber)
//plzstop_FIELD(KTHREAD, 0x084, ULONG, Spare1)
//plzstop_FIELD(KTHREAD, 0x088, PVOID, FirstArgument)
//plzstop_FIELD(KTHREAD, 0x090, PKTRAP_FRAME, TrapFrame)
//plzstop_FIELD(KTHREAD, 0x098, KAPC_STATE, ApcState)
//plzstop_FIELD(KTHREAD, 0x0C3, CHAR, Priority)
//plzstop_FIELD(KTHREAD, 0x0C4, ULONG, UserIdealProcessor)
//plzstop_FIELD(KTHREAD, 0x0C8, LONG64, WaitStatus)
//plzstop_FIELD(KTHREAD, 0x0D0, PKWAIT_BLOCK, WaitBlockList)
//plzstop_FIELD(KTHREAD, 0x0D8, LIST_ENTRY, WaitListEntry)
//plzstop_FIELD(KTHREAD, 0x0D8, SINGLE_LIST_ENTRY, SwapListEntry)
//plzstop_FIELD(KTHREAD, 0x0E8, PKQUEUE, Queue)
//plzstop_FIELD(KTHREAD, 0x0F0, PVOID, Teb)
//plzstop_FIELD(KTHREAD, 0x0F8, ULONG64, RelativeTimerBias)
//plzstop_FIELD(KTHREAD, 0x100, KTIMER, Timer)
//plzstop_FIELD(KTHREAD, 0x140, KWAIT_BLOCK[4], WaitBlock)
//plzstop_FIELD(KTHREAD, 0x154, ULONG, ContextSwitches)
//plzstop_FIELD(KTHREAD, 0x184, UCHAR, State)
//plzstop_FIELD(KTHREAD, 0x185, CHAR, NpxState)
//plzstop_FIELD(KTHREAD, 0x186, UCHAR, WaitIrql)
//plzstop_FIELD(KTHREAD, 0x187, CHAR, WaitMode)
//plzstop_FIELD(KTHREAD, 0x1B4, ULONG, WaitTime)
//plzstop_FIELD(KTHREAD, 0x1E4, SHORT, KernelApcDisable)
//plzstop_FIELD(KTHREAD, 0x1E6, SHORT, SpecialApcDisable)
//plzstop_FIELD(KTHREAD, 0x1E4, ULONG, CombinedApcDisable)
//plzstop_FIELD(KTHREAD, 0x168, KTHREAD_COUNTERS*, ThreadCounters)
//plzstop_FIELD(KTHREAD, 0x198, PXSTATE_SAVE, XStateSave)
//plzstop_FIELD(KTHREAD, 0x1C8, PVOID, Win32Thread)
//plzstop_FIELD(KTHREAD, 0x1F0, struct _UMS_CONTROL_BLOCK*, Ucb)
//plzstop_FIELD(KTHREAD, 0x1F8, struct _KUMS_CONTEXT_HEADER*, Uch)
//plzstop_FIELD(KTHREAD, 0x200, PVOID, TebMappedLowVa)
//plzstop_FIELD(KTHREAD, 0x208, LIST_ENTRY, QueueListEntry)
//plzstop_FIELD(KTHREAD, 0x218, ULONG, NextProcessor)
//plzstop_FIELD(KTHREAD, 0x21C, ULONG, DeferredProcessor)
//plzstop_FIELD(KTHREAD, 0x220, PKPROCESS, Process)
//plzstop_FIELD(KTHREAD, 0x228, GROUP_AFFINITY, UserAffinity)
//plzstop_FIELD(KTHREAD, 0x232, CHAR, PreviousMode)
//plzstop_FIELD(KTHREAD, 0x233, CHAR, BasePriority)
//plzstop_FIELD(KTHREAD, 0x234, CHAR, PriorityDecrement)
//plzstop_FIELD(KTHREAD, 0x235, UCHAR, Preempted)
//plzstop_FIELD(KTHREAD, 0x236, UCHAR, AdjustReason)
//plzstop_FIELD(KTHREAD, 0x237, CHAR, AdjustIncrement)
//plzstop_FIELD(KTHREAD, 0x238, GROUP_AFFINITY, Affinity)
//plzstop_FIELD(KTHREAD, 0x242, UCHAR, ApcStateIndex)
//plzstop_FIELD(KTHREAD, 0x243, UCHAR, WaitBlockCount)
//plzstop_FIELD(KTHREAD, 0x244, ULONG, IdealProcessor)
//plzstop_FIELD(KTHREAD, 0x248, KAPC_STATE*[2], ApcStatePointer)
//plzstop_FIELD(KTHREAD, 0x258, KAPC_STATE, SavedApcState)
//plzstop_FIELD(KTHREAD, 0x283, UCHAR, WaitReason)
//plzstop_FIELD(KTHREAD, 0x284, CHAR, SuspendCount)
//plzstop_FIELD(KTHREAD, 0x285, CHAR, Saturation)
//plzstop_FIELD(KTHREAD, 0x286, USHORT, SListFaultCount)
//plzstop_FIELD(KTHREAD, 0x288, KAPC, SchedulerApc)
//plzstop_FIELD(KTHREAD, 0x289, UCHAR, ResourceIndex)
//plzstop_FIELD(KTHREAD, 0x28B, UCHAR, QuantumReset)
//plzstop_FIELD(KTHREAD, 0x28C, ULONG, KernelTime)
//plzstop_FIELD(KTHREAD, 0x2C8, PKPRCB, WaitPrcb)
//plzstop_FIELD(KTHREAD, 0x2D0, PVOID, LegoData)
//plzstop_FIELD(KTHREAD, 0x2DB, UCHAR, CallbackNestingLevel)
//plzstop_FIELD(KTHREAD, 0x2DC, ULONG, UserTime)
//plzstop_FIELD(KTHREAD, 0x2E0, KEVENT, SuspendEvent)
//plzstop_FIELD(KTHREAD, 0x2F8, LIST_ENTRY, ThreadListEntry)
//plzstop_FIELD(KTHREAD, 0x308, LIST_ENTRY, MutantListHead)
//plzstop_FIELD(KTHREAD, 0x318, LONG64, ReadOperationCount)
//plzstop_FIELD(KTHREAD, 0x320, LONG64, WriteOperationCount)
//plzstop_FIELD(KTHREAD, 0x328, LONG64, OtherOperationCount)
//plzstop_FIELD(KTHREAD, 0x330, LONG64, ReadTransferCount)
//plzstop_FIELD(KTHREAD, 0x338, LONG64, WriteTransferCount)
//plzstop_FIELD(KTHREAD, 0x340, LONG64, OtherTransferCount)
