/* Version definitions */
#undef NTDDI_VERSION
#define NTDDI_VERSION NTDDI_VISTA
#undef _WIN32_WINNT
#define _WIN32_WINNT _WIN32_WINNT_VISTA

#include <ntifs.h>
#include <ndk/ntndk.h>

#define //plzstop_FIELD(Type, Offset, MemberType, MemberName) \
    //plzstop(FIELD_OFFSET(Type, MemberName) == Offset); \
    //plzstop(FIELD_SIZE(Type, MemberName) == sizeof(MemberType));

/* KTHREAD */
//plzstop_FIELD(KTHREAD, 0x000, DISPATCHER_HEADER, Header)
//plzstop_FIELD(KTHREAD, 0x018, ULONG64, CycleTime)
//plzstop_FIELD(KTHREAD, 0x020, ULONG64, QuantumTarget)
//plzstop_FIELD(KTHREAD, 0x028, PVOID, InitialStack)
//plzstop_FIELD(KTHREAD, 0x030, PVOID, StackLimit)
//plzstop_FIELD(KTHREAD, 0x038, PVOID, KernelStack)
//plzstop_FIELD(KTHREAD, 0x040, ULONG64, ThreadLock)
//plzstop_FIELD(KTHREAD, 0x048, KAPC_STATE, ApcState)
//plzstop_FIELD(KTHREAD, 0x048, UCHAR[43], ApcStateFill)
//plzstop_FIELD(KTHREAD, 0x073, CHAR, Priority)
//plzstop_FIELD(KTHREAD, 0x074, USHORT, NextProcessor)
//plzstop_FIELD(KTHREAD, 0x076, USHORT, DeferredProcessor)
//plzstop_FIELD(KTHREAD, 0x078, ULONG64, ApcQueueLock)
//plzstop_FIELD(KTHREAD, 0x080, LONG64, WaitStatus)
//plzstop_FIELD(KTHREAD, 0x088, PKWAIT_BLOCK, WaitBlockList)
//plzstop_FIELD(KTHREAD, 0x088, PKGATE, GateObject)
//plzstop_FIELD(KTHREAD, 0x090, LONG, MiscFlags)
//plzstop_FIELD(KTHREAD, 0x094, UCHAR, WaitReason)
//plzstop_FIELD(KTHREAD, 0x095, UCHAR, SwapBusy)
//plzstop_FIELD(KTHREAD, 0x096, UCHAR[2], Alerted)
//plzstop_FIELD(KTHREAD, 0x098, LIST_ENTRY, WaitListEntry)
//plzstop_FIELD(KTHREAD, 0x098, SINGLE_LIST_ENTRY, SwapListEntry)
//plzstop_FIELD(KTHREAD, 0x0A8, PKQUEUE, Queue)
//plzstop_FIELD(KTHREAD, 0x0B0, PVOID, Teb)
//plzstop_FIELD(KTHREAD, 0x0B8, KTIMER, Timer)
//plzstop_FIELD(KTHREAD, 0x0B8, UCHAR[60], TimerFill)
//plzstop_FIELD(KTHREAD, 0x0F4, LONG, ThreadFlags)
//plzstop_FIELD(KTHREAD, 0x0F8, KWAIT_BLOCK[4], WaitBlock)
//plzstop_FIELD(KTHREAD, 0x0F8, UCHAR[43], WaitBlockFill0)
//plzstop_FIELD(KTHREAD, 0x123, UCHAR, IdealProcessor)
//plzstop_FIELD(KTHREAD, 0x0F8, UCHAR[91], WaitBlockFill1)
//plzstop_FIELD(KTHREAD, 0x153, CHAR, PreviousMode)
//plzstop_FIELD(KTHREAD, 0x0F8, UCHAR[139], WaitBlockFill2)
//plzstop_FIELD(KTHREAD, 0x183, UCHAR, ResourceIndex)
//plzstop_FIELD(KTHREAD, 0x0F8, UCHAR[187], WaitBlockFill3)
//plzstop_FIELD(KTHREAD, 0x1B3, UCHAR, LargeStack)
//plzstop_FIELD(KTHREAD, 0x0F8, UCHAR[44], WaitBlockFill4)
//plzstop_FIELD(KTHREAD, 0x124, ULONG, ContextSwitches)
//plzstop_FIELD(KTHREAD, 0x0F8, UCHAR[92], WaitBlockFill5)
//plzstop_FIELD(KTHREAD, 0x154, UCHAR, State)
//plzstop_FIELD(KTHREAD, 0x155, UCHAR, NpxState)
//plzstop_FIELD(KTHREAD, 0x156, UCHAR, WaitIrql)
//plzstop_FIELD(KTHREAD, 0x157, CHAR, WaitMode)
//plzstop_FIELD(KTHREAD, 0x0F8, UCHAR[140], WaitBlockFill6)
//plzstop_FIELD(KTHREAD, 0x184, ULONG, WaitTime)
//plzstop_FIELD(KTHREAD, 0x0F8, UCHAR[188], WaitBlockFill7)
//plzstop_FIELD(KTHREAD, 0x1B4, SHORT, KernelApcDisable)
//plzstop_FIELD(KTHREAD, 0x1B6, SHORT, SpecialApcDisable)
//plzstop_FIELD(KTHREAD, 0x1B4, ULONG, CombinedApcDisable)
//plzstop_FIELD(KTHREAD, 0x1B8, LIST_ENTRY, QueueListEntry)
//plzstop_FIELD(KTHREAD, 0x1C8, PKTRAP_FRAME, TrapFrame)
//plzstop_FIELD(KTHREAD, 0x1D0, PVOID, FirstArgument)
//plzstop_FIELD(KTHREAD, 0x1D8, PVOID, CallbackStack)
//plzstop_FIELD(KTHREAD, 0x1D8, ULONG64, CallbackDepth)
//plzstop_FIELD(KTHREAD, 0x1E0, UCHAR, ApcStateIndex)
//plzstop_FIELD(KTHREAD, 0x1E1, CHAR, BasePriority)
//plzstop_FIELD(KTHREAD, 0x1E2, CHAR, PriorityDecrement)
//plzstop_FIELD(KTHREAD, 0x1E3, UCHAR, Preempted)
//plzstop_FIELD(KTHREAD, 0x1E4, UCHAR, AdjustReason)
//plzstop_FIELD(KTHREAD, 0x1E5, CHAR, AdjustIncrement)
//plzstop_FIELD(KTHREAD, 0x1E6, UCHAR, Spare01)
//plzstop_FIELD(KTHREAD, 0x1E7, CHAR, Saturation)
//plzstop_FIELD(KTHREAD, 0x1E8, ULONG, SystemCallNumber)
//plzstop_FIELD(KTHREAD, 0x1EC, ULONG, Spare02)
//plzstop_FIELD(KTHREAD, 0x1F0, ULONG64, UserAffinity)
//plzstop_FIELD(KTHREAD, 0x1F8, PKPROCESS, Process)
//plzstop_FIELD(KTHREAD, 0x200, ULONG64, Affinity)
//plzstop_FIELD(KTHREAD, 0x208, PKAPC_STATE[2], ApcStatePointer)
//plzstop_FIELD(KTHREAD, 0x218, KAPC_STATE, SavedApcState)
//plzstop_FIELD(KTHREAD, 0x218, UCHAR[43], SavedApcStateFill)
//plzstop_FIELD(KTHREAD, 0x243, CHAR, FreezeCount)
//plzstop_FIELD(KTHREAD, 0x244, CHAR, SuspendCount)
//plzstop_FIELD(KTHREAD, 0x245, UCHAR, UserIdealProcessor)
//plzstop_FIELD(KTHREAD, 0x246, UCHAR, Spare03)
//plzstop_FIELD(KTHREAD, 0x247, UCHAR, CodePatchInProgress)
//plzstop_FIELD(KTHREAD, 0x248, PVOID, Win32Thread)
//plzstop_FIELD(KTHREAD, 0x250, PVOID, StackBase)
//plzstop_FIELD(KTHREAD, 0x258, KAPC, SuspendApc)
//plzstop_FIELD(KTHREAD, 0x258, UCHAR, SuspendApcFill0)
//plzstop_FIELD(KTHREAD, 0x259, CHAR, Spare04)
//plzstop_FIELD(KTHREAD, 0x258, UCHAR[3], SuspendApcFill1)
//plzstop_FIELD(KTHREAD, 0x25B, UCHAR, QuantumReset)
//plzstop_FIELD(KTHREAD, 0x258, UCHAR[4], SuspendApcFill2)
//plzstop_FIELD(KTHREAD, 0x25C, ULONG, KernelTime)
//plzstop_FIELD(KTHREAD, 0x258, UCHAR[64], SuspendApcFill3)
//plzstop_FIELD(KTHREAD, 0x298, PKPRCB, WaitPrcb)
//plzstop_FIELD(KTHREAD, 0x258, UCHAR[72], SuspendApcFill4)
//plzstop_FIELD(KTHREAD, 0x2A0, PVOID, LegoData)
//plzstop_FIELD(KTHREAD, 0x258, UCHAR[83], SuspendApcFill5)
//plzstop_FIELD(KTHREAD, 0x2AB, UCHAR, PowerState)
//plzstop_FIELD(KTHREAD, 0x2AC, ULONG, UserTime)
//plzstop_FIELD(KTHREAD, 0x2B0, KSEMAPHORE, SuspendSemaphore)
//plzstop_FIELD(KTHREAD, 0x2B0, UCHAR[28], SuspendSemaphorefill)
//plzstop_FIELD(KTHREAD, 0x2CC, ULONG, SListFaultCount)
//plzstop_FIELD(KTHREAD, 0x2D0, LIST_ENTRY, ThreadListEntry)
//plzstop_FIELD(KTHREAD, 0x2E0, LIST_ENTRY, MutantListHead)
//plzstop_FIELD(KTHREAD, 0x2F0, PVOID, SListFaultAddress)
//plzstop_FIELD(KTHREAD, 0x2F8, LONG64, ReadOperationCount)
//plzstop_FIELD(KTHREAD, 0x300, LONG64, WriteOperationCount)
//plzstop_FIELD(KTHREAD, 0x308, LONG64, OtherOperationCount)
//plzstop_FIELD(KTHREAD, 0x310, LONG64, ReadTransferCount)
//plzstop_FIELD(KTHREAD, 0x318, LONG64, WriteTransferCount)
//plzstop_FIELD(KTHREAD, 0x320, LONG64, OtherTransferCount)
//plzstop_FIELD(KTHREAD, 0x328, PVOID, MdlForLockedTeb)
