/* Version definitions */
#undef NTDDI_VERSION
#define NTDDI_VERSION NTDDI_VISTA
#undef _WIN32_WINNT
#define _WIN32_WINNT _WIN32_WINNT_VISTA

#include <ntifs.h>
#include <ndk/ntndk.h>

#define //plzstop_FIELD(Type, Offset, MemberType, MemberName) \
    //plzstop(FIELD_OFFSET(Type, MemberName) == Offset); \
    //plzstop(FIELD_SIZE(Type, MemberName) == sizeof(MemberType));

/* KTHREAD */
//plzstop_FIELD(KTHREAD, 0x000, DISPATCHER_HEADER, Header)
//plzstop_FIELD(KTHREAD, 0x010, ULONG64, CycleTime)
//plzstop_FIELD(KTHREAD, 0x018, ULONG, HighCycleTime)
//plzstop_FIELD(KTHREAD, 0x020, ULONG64, QuantumTarget)
//plzstop_FIELD(KTHREAD, 0x028, PVOID, InitialStack)
//plzstop_FIELD(KTHREAD, 0x02C, PVOID, StackLimit)
//plzstop_FIELD(KTHREAD, 0x030, PVOID, KernelStack)
//plzstop_FIELD(KTHREAD, 0x034, ULONG, ThreadLock)
//plzstop_FIELD(KTHREAD, 0x038, KAPC_STATE, ApcState)
//plzstop_FIELD(KTHREAD, 0x038, UCHAR[23], ApcStateFill)
//plzstop_FIELD(KTHREAD, 0x04F, CHAR, Priority)
//plzstop_FIELD(KTHREAD, 0x050, USHORT, NextProcessor)
//plzstop_FIELD(KTHREAD, 0x052, USHORT, DeferredProcessor)
//plzstop_FIELD(KTHREAD, 0x054, ULONG, ApcQueueLock)
//plzstop_FIELD(KTHREAD, 0x058, ULONG, ContextSwitches)
//plzstop_FIELD(KTHREAD, 0x05C, UCHAR, State)
//plzstop_FIELD(KTHREAD, 0x05D, UCHAR, NpxState)
//plzstop_FIELD(KTHREAD, 0x05E, UCHAR, WaitIrql)
//plzstop_FIELD(KTHREAD, 0x05F, CHAR, WaitMode)
//plzstop_FIELD(KTHREAD, 0x060, LONG, WaitStatus)
//plzstop_FIELD(KTHREAD, 0x064, PKWAIT_BLOCK, WaitBlockList)
//plzstop_FIELD(KTHREAD, 0x064, PKGATE, GateObject)
//plzstop_FIELD(KTHREAD, 0x068, LONG, MiscFlags)
//plzstop_FIELD(KTHREAD, 0x06C, UCHAR, WaitReason)
//plzstop_FIELD(KTHREAD, 0x06D, UCHAR, SwapBusy)
//plzstop_FIELD(KTHREAD, 0x06E, UCHAR[2], Alerted)
//plzstop_FIELD(KTHREAD, 0x070, LIST_ENTRY, WaitListEntry)
//plzstop_FIELD(KTHREAD, 0x070, SINGLE_LIST_ENTRY, SwapListEntry)
//plzstop_FIELD(KTHREAD, 0x078, PKQUEUE, Queue)
//plzstop_FIELD(KTHREAD, 0x07C, ULONG, WaitTime)
//plzstop_FIELD(KTHREAD, 0x080, SHORT, KernelApcDisable)
//plzstop_FIELD(KTHREAD, 0x082, SHORT, SpecialApcDisable)
//plzstop_FIELD(KTHREAD, 0x080, ULONG, CombinedApcDisable)
//plzstop_FIELD(KTHREAD, 0x084, PVOID, Teb)
//plzstop_FIELD(KTHREAD, 0x088, KTIMER, Timer)
//plzstop_FIELD(KTHREAD, 0x088, UCHAR[40], TimerFill)
//plzstop_FIELD(KTHREAD, 0x0B0, LONG, ThreadFlags)
//plzstop_FIELD(KTHREAD, 0x0B8, KWAIT_BLOCK[4], WaitBlock)
//plzstop_FIELD(KTHREAD, 0x0B8, UCHAR[23], WaitBlockFill0)
//plzstop_FIELD(KTHREAD, 0x0CF, UCHAR, IdealProcessor)
//plzstop_FIELD(KTHREAD, 0x0B8, UCHAR[47], WaitBlockFill1)
//plzstop_FIELD(KTHREAD, 0x0E7, CHAR, PreviousMode)
//plzstop_FIELD(KTHREAD, 0x0B8, UCHAR[71], WaitBlockFill2)
//plzstop_FIELD(KTHREAD, 0x0FF, UCHAR, ResourceIndex)
//plzstop_FIELD(KTHREAD, 0x0B8, UCHAR[95], WaitBlockFill3)
//plzstop_FIELD(KTHREAD, 0x117, UCHAR, LargeStack)
//plzstop_FIELD(KTHREAD, 0x118, LIST_ENTRY, QueueListEntry)
//plzstop_FIELD(KTHREAD, 0x120, PKTRAP_FRAME, TrapFrame)
//plzstop_FIELD(KTHREAD, 0x124, PVOID, FirstArgument)
//plzstop_FIELD(KTHREAD, 0x128, PVOID, CallbackStack)
//plzstop_FIELD(KTHREAD, 0x128, ULONG, CallbackDepth)
//plzstop_FIELD(KTHREAD, 0x12C, PVOID, ServiceTable)
//plzstop_FIELD(KTHREAD, 0x130, UCHAR, ApcStateIndex)
//plzstop_FIELD(KTHREAD, 0x131, CHAR, BasePriority)
//plzstop_FIELD(KTHREAD, 0x132, CHAR, PriorityDecrement)
//plzstop_FIELD(KTHREAD, 0x133, UCHAR, Preempted)
//plzstop_FIELD(KTHREAD, 0x134, UCHAR, AdjustReason)
//plzstop_FIELD(KTHREAD, 0x135, CHAR, AdjustIncrement)
//plzstop_FIELD(KTHREAD, 0x136, UCHAR, Spare01)
//plzstop_FIELD(KTHREAD, 0x137, CHAR, Saturation)
//plzstop_FIELD(KTHREAD, 0x138, ULONG, SystemCallNumber)
//plzstop_FIELD(KTHREAD, 0x13C, ULONG, Spare02)
//plzstop_FIELD(KTHREAD, 0x140, ULONG, UserAffinity)
//plzstop_FIELD(KTHREAD, 0x144, PKPROCESS, Process)
//plzstop_FIELD(KTHREAD, 0x148, ULONG, Affinity)
//plzstop_FIELD(KTHREAD, 0x14C, PKAPC_STATE[2], ApcStatePointer)
//plzstop_FIELD(KTHREAD, 0x154, KAPC_STATE, SavedApcState)
//plzstop_FIELD(KTHREAD, 0x154, UCHAR[23], SavedApcStateFill)
//plzstop_FIELD(KTHREAD, 0x16B, CHAR, FreezeCount)
//plzstop_FIELD(KTHREAD, 0x16C, CHAR, SuspendCount)
//plzstop_FIELD(KTHREAD, 0x16D, UCHAR, UserIdealProcessor)
//plzstop_FIELD(KTHREAD, 0x16E, UCHAR, Spare03)
//plzstop_FIELD(KTHREAD, 0x16F, UCHAR, OtherPlatformFill)
//plzstop_FIELD(KTHREAD, 0x170, PVOID, Win32Thread)
//plzstop_FIELD(KTHREAD, 0x174, PVOID, StackBase)
//plzstop_FIELD(KTHREAD, 0x178, KAPC, SuspendApc)
//plzstop_FIELD(KTHREAD, 0x178, UCHAR, SuspendApcFill0)
//plzstop_FIELD(KTHREAD, 0x179, CHAR, Spare04)
//plzstop_FIELD(KTHREAD, 0x178, UCHAR[3], SuspendApcFill1)
//plzstop_FIELD(KTHREAD, 0x17B, UCHAR, QuantumReset)
//plzstop_FIELD(KTHREAD, 0x178, UCHAR[4], SuspendApcFill2)
//plzstop_FIELD(KTHREAD, 0x17C, ULONG, KernelTime)
//plzstop_FIELD(KTHREAD, 0x178, UCHAR[36], SuspendApcFill3)
//plzstop_FIELD(KTHREAD, 0x19C, PKPRCB, WaitPrcb)
//plzstop_FIELD(KTHREAD, 0x178, UCHAR[40], SuspendApcFill4)
//plzstop_FIELD(KTHREAD, 0x1A0, PVOID, LegoData)
//plzstop_FIELD(KTHREAD, 0x178, UCHAR[47], SuspendApcFill5)
//plzstop_FIELD(KTHREAD, 0x1A7, UCHAR, PowerState)
//plzstop_FIELD(KTHREAD, 0x1A8, ULONG, UserTime)
//plzstop_FIELD(KTHREAD, 0x1AC, KSEMAPHORE, SuspendSemaphore)
//plzstop_FIELD(KTHREAD, 0x1AC, UCHAR[20], SuspendSemaphorefill)
//plzstop_FIELD(KTHREAD, 0x1C0, ULONG, SListFaultCount)
//plzstop_FIELD(KTHREAD, 0x1C4, LIST_ENTRY, ThreadListEntry)
//plzstop_FIELD(KTHREAD, 0x1CC, LIST_ENTRY, MutantListHead)
//plzstop_FIELD(KTHREAD, 0x1D4, PVOID, SListFaultAddress)
//plzstop_FIELD(KTHREAD, 0x1D8, PVOID, MdlForLockedTeb)
